### ISSUE TITLE
Would model weights be available on HuggingFace?

### ISSUE THREAD

**Issue by kirill-vas** [EngineeringSoftware/codeditor#2]
Hello!

In your paper, you have several fine-tuned models in addition to Codeditor (e.g. CodeT5-Translation, CodeT-Update). Have you considered sharing the model weights for some of these models, similarly to how CoditT5 was shared on HuggingFace at [https://huggingface.co/JiyangZhang/CoditT5](https://huggingface.co/JiyangZhang/CoditT5)?

I'm looking to try and reproduce some of the results and then try the trained models on private repos of java and C#; would be great not to have to train new models :)

**Comment by JiyangZhang** [comment]
Hi, I will work on that! Probably finish that next week!

Thanks for the issue.

**Comment by JiyangZhang** [comment]
Hi,

Because of some issue on our side, the fine-tuned CodeT5-Translation models' checkpoints are missing. But it should be easy to fine-tune on our dataset with huggingface interface: [see here](https://medium.com/nlplanet/a-full-guide-to-finetuning-t5-for-text2text-and-building-a-demo-with-streamlit-c72009631887)

I uploaded our EditTranslation model to huggingface for you to check and further finetune. [EditsTranslation-java2cs](https://huggingface.co/EngineeringSoftware/EditsTranlation-java2cs).

Please check the updated contents in README for tutorial on how to use the model.

If you have any question, feel free to reach out.

Thank you

**Comment by the-promised-LAN** [comment]
Many thanks Jiyang! Will try this out and report back if there are any issues.

**Comment by kirill-vas** [comment]
Many thanks Jiyang! Will try this out and report back if there are any issues.
